Chapter12/mysite/blog/urls.py
from django.urls import path, register_converter
from . import views
from .converters import CodeConverter

register_converter(CodeConverter, 'code')

app_name='blog'
urlpatterns = [
    path('', views.list, name='list'),
    path('<int:id>/', views.detail, name='detail'),
    path('tag/<id>/', views.tag_list),
    path('test1/', views.test1),
    path('test2/<int:no>/', views.test2),
    path('test3/<year>/<month>/<day>/', views.test3),
    path('test4/<code:id>/', views.test4),
    path('test5/', views.test5),
    path('test6/', views.test6),
    path('test7/<no>/', views.test7),
    path('new/', views.post_create, name='create'),
    path('update/<id>/', views.post_update, name='update'),
    path('delete/<id>/', views.post_delete, name='delete'),
    path('test8/', views.test8),


]

Chapter12/mysite/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_list'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('detail/', views.cart_detail, name='cart_detail'),
    path('clear/', views.cart_clear, name='cart_clear'),
]

Chapter12/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('account/', include('account.urls')),
    path('book/', include('book.urls')),
    path('gallery/', include('gallery.urls')),
    path('cart/', include('cart.urls')),
    path('', include('shop.urls')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Chapter12/mysite/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'
urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:id>/', views.product_detail, name='product_detail'),
]

Chapter12/mysite/cart/models.py
from django.db import models

# Create your models here.

Chapter12/mysite/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i,str(i)) for i in range(1, 21) ]
class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label='수량')
    override = forms.BooleanField(
        required=False, initial=False, widget=forms.HiddenInput)

Chapter12/mysite/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail') 

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity':item['quantity'], 'override':True})
    return render(request, 'cart/detail.html', {'cart':cart})

@require_POST
def cart_clear(request):
    cart = Cart(request)
    cart.clear()
    return redirect('cart:cart_detail')

Chapter12/mysite/cart/templates/cart/detail.html
{% extends "layout.html" %}
{% load humanize %}
{% block title %} 장바구니{% endblock %}
{% block content %}
  <h3 class="text-center">장바구니</h1>
  <table class="table">
    <thead>
      <tr>
        <th>제품사진</th><th>제품명</th><th>수량</th><th>삭제</th><th>단가</th><th>금액</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}"> <img src="{{ product.image.url }}" width="50" height="50"> </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
                <form action="{% url "cart:cart_add" product.id %}" method="post">
                    {{ item.update_quantity_form.quantity }}
                    {{ item.update_quantity_form.override }}
                    <input type="submit" value="수정">
                    {% csrf_token %}
                </form>
            </td>
            <td>
              <form action="{% url "cart:cart_remove" product.id %}" method="post">
                <input type="submit" value="삭제">
                {% csrf_token %}
              </form>
            </td>
            <td>{{ item.price|intcomma }}원</td>
            <td>{{ item.total_price|intcomma }}원</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="active">
        <td>총금액</td>
        <td colspan="4"></td>
        <td>{{ cart.get_total_price|intcomma }}원</td>
     </tr>
    </tbody>
  </table>
  <p>
    <div  class="text-center">
      <a href="{% url 'shop:product_list' %}">쇼핑계속하기</a>
    </div>
    <div  class="text-right">
      <form action="{% url "cart:cart_clear" %}" method="post">
        <input type="submit" value="장바구니 비우기">
        {% csrf_token %}
      </form>
    </div>
  </p>
{% endblock %}